import { ContractData } from "../../components/table/ContractTable";

export const fakeContractData: ContractData[] = [
  {
    id: 1,
    signedBy: "John Smith",
    position: "Project Manager",
    amountByContract: 150000,
    organization: "Tech Solutions Inc.",
    dateCreated: "2024-01-15",
    noOfRequest: 12,
    contract_id: "CTR-2024-001",
  },
  {
    id: 2,
    signedBy: "Sarah Johnson",
    position: "Senior Developer",
    amountByContract: 85000,
    organization: "Digital Innovations Ltd.",
    dateCreated: "2024-01-20",
    noOfRequest: 8,
    contract_id: "CTR-2024-002",
  },
  {
    id: 3,
    signedBy: "Michael Brown",
    position: "Business Analyst",
    amountByContract: 120000,
    organization: "Global Systems Corp.",
    dateCreated: "2024-01-25",
    noOfRequest: 15,
    contract_id: "CTR-2024-003",
  },
  {
    id: 4,
    signedBy: "Emily Davis",
    position: "UI/UX Designer",
    amountByContract: 95000,
    organization: "Creative Design Studio",
    dateCreated: "2024-02-01",
    noOfRequest: 6,
    contract_id: "CTR-2024-004",
  },
  {
    id: 5,
    signedBy: "David Wilson",
    position: "DevOps Engineer",
    amountByContract: 110000,
    organization: "Cloud Solutions LLC",
    dateCreated: "2024-02-05",
    noOfRequest: 10,
    contract_id: "CTR-2024-005",
  },
  {
    id: 6,
    signedBy: "Lisa Anderson",
    position: "Product Owner",
    amountByContract: 180000,
    organization: "Innovation Labs",
    dateCreated: "2024-02-10",
    noOfRequest: 20,
    contract_id: "CTR-2024-006",
  },
  {
    id: 7,
    signedBy: "Robert Taylor",
    position: "QA Lead",
    amountByContract: 75000,
    organization: "Quality Assurance Pro",
    dateCreated: "2024-02-15",
    noOfRequest: 9,
    contract_id: "CTR-2024-007",
  },
  {
    id: 8,
    signedBy: "Jennifer Martinez",
    position: "Scrum Master",
    amountByContract: 90000,
    organization: "Agile Solutions",
    dateCreated: "2024-02-20",
    noOfRequest: 14,
    contract_id: "CTR-2024-008",
  },
  {
    id: 9,
    signedBy: "Christopher Lee",
    position: "Backend Developer",
    amountByContract: 130000,
    organization: "Data Systems Inc.",
    dateCreated: "2024-02-25",
    noOfRequest: 11,
    contract_id: "CTR-2024-009",
  },
  {
    id: 10,
    signedBy: "Amanda Garcia",
    position: "Frontend Developer",
    amountByContract: 100000,
    organization: "Web Solutions Co.",
    dateCreated: "2024-03-01",
    noOfRequest: 7,
    contract_id: "CTR-2024-010",
  },
];
